### ISSUE TITLE
点灯官方app 设备里面的调试发送数据，1886 接口，是不对用户开放吗？

### ISSUE THREAD

**Issue by blinker123** [blinker-iot/app-release#3]
抓包app 使用调试发送数据，发现是wss 协议 ，使用点灯 1886 接口，这个好像不在任何公开的使用文档里面，1886 接口的服务器也有向阿里的设备下发消息的能里，普通用户能拥有下发mqtt消息 到使用阿里的服务器的设备上吗？

**Comment by coloz** [comment]
文档一直都是开放的，当前点灯版本已经不再提供阿里broker接入，我们自己broker的接入方式可见接口文档：
https://diandeng.tech/doc/api-mqtt
